Enterprise-CMCS/macpro-mdct-seds

dev
Adjusted yarn install to use modern syntax for global installs.
Added yarn installed files to path which stops the ENOENT errors during spawn.
=> Update yarn install and add to path

services/app-api/serverless.yml
Calls were still being made to the deleted tables below in app-api/serverless.yml:
` Serverless Warning --------------------------------------
A valid service attribute to satisfy the declaration 'self:custom.tableName' could not be found.
Serverless Warning --------------------------------------
A valid service attribute to satisfy the declaration 'self:custom.atomicCounterTableName' could not be found.
Serverless Warning --------------------------------------
A valid service attribute to satisfy the declaration 'self:custom.tableArn' could not be found.
Serverless Warning --------------------------------------
A valid service attribute to satisfy the declaration 'self:custom.atomicCounterTableArn' could not be found.`
Made the following changes in attempt to resolve:
- found and removed …
=> Try to fix the deploy failure on merge

services/database/serverless.yml, services/stream-functions/serverless.yml
set tableStreamArn to work against FormAnswerTableStreamArn
=> set tableStreamArn to work against FormAnswerTableStreamArn

README.md, services/ui-src/src/components/layout/Header.js, tests/nightwatch/tests/firstTest.js
Updates to the current tests have been made to pass for the new homepage.
Readme was updated with instructions for running locally.
=> Adjust first test to pass, update readme

services/ui-src/src/scss/_buttons.scss, services/ui-src/src/scss/_variables.scss
Satisfies: #4531
Change status button colors and size by request
=> Adjust colors for status buttons

services/database/serverless.yml
fix part 2 - change table names back to correct names
=> fix part 2 - change table names back to correct names

README.md
Change the README to be more MDCT SEDS specific and include useful instructions regarding Windows VM setup and GitHub policies.
=> Update the README to reflect MDCT SEDS

src/database/schema/schema_age_ranges.json, src/database/schema/schema_state_forms.json, src/database/schema/schema_states.json, src/database/schema/schema_status.json
first pass at schema docs for age_ranges, states, status and state_forms
=> schema docs for age_ranges, states, status and state_forms

services/ui-src/src/containers/HomeState.js, services/ui-src/src/scss/_main.scss
Satisfies: [#3895](https://qmacbis.atlassian.net/browse/OY2-3895?atlOrigin=eyJpIjoiNjZlNzFiNTdhODg0NDM4ZmFmMDE2ZTFiODNkMjE5NmYiLCJwIjoiaiJ9)
- Minor copy update
- Remove bullet points from quarter list
- Remove secondary page header
=> Minor changes to State Homepage

services/database/serverless.yml, src/database/initial_data_load/21E.json, src/database/initial_data_load/age_ranges.json, src/database/initial_data_load/form_answers_21E.json, src/database/initial_data_load/state_forms.json
Create the answers entries for form 21E for AL, MD and PA for testing against.
=> Database seed 21e

services/database/serverless.yml
add dev to stages in serverless.yml to see if the seed files will deploy to dev db
=> add dev to stages in serverless.yml

services/database/serverless.yml
try it using master instead of dev since master is our dev branch
=> Attempt to seed db on master branch

services/ui-src/src/containers/Login.js
=> Replace redirectSignIn with window.location.pathname

services/ui-src/src/App.js, services/ui-src/src/components/layout/Header.js
Unknown errors are occurring with Okta login. This adds two console.log's to help trace the issues
=> Add console logs for error checking

services/database/serverless.yml, src/database/initial_data_load/auth_user.json
user_auth had numbers instead of strings for user-id's
user_auth_roles was provisioned incorrectly in serverless (id vs user-id)
=> Clean up key mismatches

services/ui-auth/serverless.yml
Added profile to scopes. This should allow additional information to be passed from cognito into react.
=> Add profile to Cognito User pool client scope

.github/workflows/deploy.yml, services/database/serverless.yml, services/ui-auth/serverless.yml, services/ui-src/src/App.js, services/ui-src/src/components/layout/Header.js, services/ui-src/src/libs/user.js
Add family_name and given_name to schema
Swap return `Auth.currentUserInfo()` for `Auth.currentAuthenticatedUser`
Return table name to `auth-user-roles`
=> Minor tweaks to match macpro

services/ui-src/src/App.js, services/ui-src/src/components/layout/Header.js
Use new payload schema to set user info
=> Update login logic

services/ui-src/src/App.js, services/ui-src/src/components/layout/Header.js, services/ui-src/src/containers/Profile.js, services/ui-src/src/libs/user.js
Change error checking in App.js
Adjust header to check for payload email address
Update profile page (note: profile page needs to wait for the user module before completion)
Add testing code in
=> Update login functionality

services/ui-auth/serverless.yml, services/ui-src/src/App.js, services/ui-src/src/components/layout/Header.js
Add isMemberOf and associated changes
=> Add debug code, fix local login in header

services/ui-src/src/components/CertificationTab.js
**Linked Issue:**
None. 
**Overview:**
These are edits from Manager Review. 
**Files changed (1):**
`services/ui-src/src/components/CertificationTab.js`
"SEDs" changed to "SEDS" 
Fixed proptype warnings
=> Feature/certification-tab, MR edits

services/ui-auth/serverless.yml, services/ui-src/src/App.js, services/ui-src/src/components/layout/Header.js
Log user out of cognito as well as local
Minor edit to serverless config, set ismemberof to custom:ismemberof
=> Add cognito logout to logout handler

services/app-api/handlers/forms/getFormsList.js, services/app-api/libs/dynamodb-lib.js, services/app-api/serverless.yml, services/ui-src/src/containers/Quarterly.js, services/ui-src/src/libs/api.js, services/ui-src/src/store/reducers/stateData.js
for ticket [4010](https://qmacbis.atlassian.net/secure/RapidBoard.jspa?rapidView=184&modal=detail&selectedIssue=OY2-4010)
Form name might need to be updated on the frontend.
=> List state forms per state,year,quarter. Frontend displays list

services/database/serverless.yml
=> feature-use-api db fix step 2

services/ui-src/src/components/users/UserEdit.js, services/ui-src/src/components/users/Users.js
=> Feature user api tweaks

services/ui-src/src/components/users/UserEdit.js, services/ui-src/src/components/users/Users.js
incorporating  UI changes for user list and fix minor bug when hovering over Print and Download buttons
https://user-images.githubusercontent.com/78756196/108258025-9576f400-712d-11eb-8f4f-213f592b6c0a.mov
=> Feature user api

services/app-api/handlers/forms/getFormsList.js, services/app-api/handlers/users/get.js, services/app-api/serverless.yml, services/ui-src/src/components/layout/Header.js, services/ui-src/src/containers/LocalLogin.js, services/ui-src/src/containers/Profile.js, services/ui-src/src/libs/api.js, services/ui-src/src/store/reducers/stateData.js
Update local login to match seeded data in DB.
Update calls on profile.js to pull from correct payload regardless of local or remote login.
Switch getUser (single user) to a get request
=> Update local login and fix profile page

.github/workflows/style_checks.yml, services/app-api/handlers/forms/getFormsList.js, services/ui-src/src/containers/Quarterly.js
This is to finish up ticket [4574](https://qmacbis.atlassian.net/secure/RapidBoard.jspa?rapidView=184&modal=detail&selectedIssue=OY2-4574&quickFilter=388) The table name in GetFormsList.js has been replaced with an environment variable.
=> Updated the table name to pull from environment variable

services/app-api/handlers/forms/getFormsList.js
to StateFormsTableName (global declaration) from STATE_FORMS_TABLE_NAME
=> change TableName parameter value

services/app-api/handlers/create.js, services/app-api/handlers/delete.js, services/app-api/handlers/get.js, services/app-api/handlers/list.js, services/app-api/handlers/update.js
and see if this fixes the /users pages
=> change tableName in params to be AuthUserTableName

services/app-api/handlers/users/activation.js, services/app-api/handlers/users/create.js, services/app-api/handlers/users/delete.js, services/app-api/handlers/users/get.js, services/app-api/handlers/users/list.js, services/app-api/handlers/users/update.js
User env var names from serverless.yml (not .env)
=> Update TableName to correct env vars

services/database/serverless.yml, src/database/initial_data_load/21E.json, src/database/initial_data_load/64_21E.json, src/database/initial_data_load/form_answers_21E_AL.json, src/database/initial_data_load/form_answers_21E_MD.json, src/database/initial_data_load/form_answers_21E_PA.json, src/database/initial_data_load/form_answers_64_21E_MD.json, src/database/initial_data_load/form_answers_64_21E_PA.json, src/database/initial_data_load/state_forms.json
Satisfies [OY2-2976](https://qmacbis.atlassian.net/browse/OY2-2976)
- Create the form questions for 2021 in 64_21E.json and seed to the db table form_questions
- Add the form for each state in state_forms.json 
- Create the test state responses for AL, MD & PA and seed to the db table form_answers
1. form_answers_64_21E_AL.json
2. form_answers_64_21E_MD.json
3. form_answers_64_21E_PA.json
Additionally, add age_ranges.rangeID to 21E form_answers for AL, MD & PA and forms.form_id to 21E form_questions for continuity sake/ease of use later.
=> Create JSON for Form 64.21E

services/app-api/serverless.yml, services/ui-src/src/containers/HomeState.js
Attempting Doug's recommended solution to add the auth-users table to the LamdaApiRole policy allow permissions.
Also, change the default testing state to AL (from AK) since we have data for AL in the database to test/work against.
=> Bugfix api users

services/database/serverless.yml, src/database/initial_data_load/GenderRaceEthnicity.json, src/database/initial_data_load/form_answers_GRE_AL.json, src/database/initial_data_load/form_answers_GRE_MD.json, src/database/initial_data_load/form_answers_GRE_PA.json, src/database/initial_data_load/forms.json, src/database/initial_data_load/state_forms.json
-for ticket [3005](https://qmacbis.atlassian.net/secure/RapidBoard.jspa?rapidView=184&modal=detail&selectedIssue=OY2-3005)
-created json for GRE form
-created answers json for the PA,AL,MD
-added to initial load yml file
=> Gender Race Ethnicity form and answers

services/ui-src/src/libs/api.js
Add auth token to headers for the api.
Add in debug code
=> Add user auth token to headers

services/database/serverless.yml, src/database/initial_data_load/21PW.json, src/database/initial_data_load/age_ranges.json, src/database/initial_data_load/form_answers_21PW_AL.json, src/database/initial_data_load/form_answers_21PW_MD.json, src/database/initial_data_load/form_answers_21PW_PA.json, src/database/initial_data_load/forms.json, src/database/initial_data_load/state_forms.json
For ticket 5051[(https://qmacbis.atlassian.net/secure/RapidBoard.jspa?rapidView=184&modal=detail&selectedIssue=OY2-5051)
Add age range, form record, reference to json files in serverless, and add 3 records to state_forms
=> Create 21PW form and answer. 

services/app-api/serverless.yml, services/stream-functions/serverless.yml, services/ui-auth/serverless.yml, services/ui-src/serverless.yml, services/ui/serverless.yml, services/uploads/serverless.yml
Purpose of this PR is to fix the issue with termination protection on every stack which is preventing them to delete, added a termination stages on each layer of our application
=> add set stages for termination protection

services/ui-src/src/components/layout/Header.js, services/ui-src/src/containers/Login.js, services/ui-src/src/containers/NewAmendment.js, services/ui-src/src/containers/Profile.js, services/ui-src/src/containers/Signup.js, services/ui-src/src/libs/user.js
=> Cherry pick fixauth to master from 0a81886901c003330c47ae55080765f76d4b53f9 and prior

services/app-api/cognitoAuth/authProvider.js, services/app-api/handlers/users/post/getUserByUsername.js, services/app-api/package.json, services/app-api/yarn.lock, services/ui-src/src/containers/Signup.js, services/ui-src/src/libs/api.js, src/database/initial_data_load/form_answers_21PW_AL.json, src/database/initial_data_load/form_answers_21PW_MD.json, src/database/initial_data_load/form_answers_21PW_PA.json, src/database/initial_data_load/state_forms.json
first attempt at retriving cognito attributes
=> first attempt at retriving cognito attributes

services/ui-src/src/App.js, services/ui-src/src/Routes.js, services/ui-src/src/components/users/Users.js, services/ui-src/src/containers/Home.js, services/ui-src/src/libs/api.js
Commenting out a fair amount lot of functionality.
The app is functional.  We were able to login, go to the users route, and add a new user.
API functionality wasn't broken or changed.
The nature of the 403 seems to be when requesting a route directly from the browser URL bar... since bucket/users does not exist, cloudfront sends you a 403 before sending you correctly via the router.
This behavior is also seen in the quickstart and is considered nominal.
=> March 9 meeting mods

services/app-api/handlers/users/get/getUserById.js, services/ui-src/src/App.js, services/ui-src/src/Routes.js, services/ui-src/src/components/users/UserAdd.js, services/ui-src/src/components/users/UserEdit.js, services/ui-src/src/components/users/Users.js, services/ui-src/src/containers/LocalLogin.js, services/ui-src/src/containers/Profile.js, services/ui-src/src/containers/Signup.js, services/ui-src/src/libs/api.js, src/database/initial_data_load/auth_user.json
This PR tackles an array of adjustments that are needed after addressing 403 errors.
Correct issues with isActive always returning false. The issue stemmed from pulling isActive from the wrong location. Pulling from the DB data first is the way to go.
Convert States from String to List (Array). Previously, states were stored in a hyphen separated string. This converts to a safer data type of list. Accompanying functions were updated to support this change. Also updated localLogin and auth_users.json to reflect these changes.
Updated getUser to getUserById across the project for clarity and to remove 403 error
=> Tweaks after fixing API connections

package-lock.json, src/database/initial_data_load/21E.json, src/database/initial_data_load/21PW.json, src/database/initial_data_load/64EC.json, src/database/initial_data_load/64_21E.json, src/database/initial_data_load/form_answers_21E_AL.json, src/database/initial_data_load/form_answers_21E_MD.json, src/database/initial_data_load/form_answers_21E_PA.json, src/database/initial_data_load/form_answers_21PW_AL.json, src/database/initial_data_load/form_answers_21PW_MD.json, src/database/initial_data_load/form_answers_21PW_PA.json, src/database/initial_data_load/form_answers_64EC_AL.json, src/database/initial_data_load/form_answers_64EC_MD.json, src/database/initial_data_load/form_answers_64EC_PA.json, src/database/initial_data_load/form_answers_64_21E_AL.json, src/database/initial_data_load/form_answers_64_21E_MD.json, src/database/initial_data_load/form_answers_64_21E_PA.json
For ticket [6538](https://qmacbis.atlassian.net/secure/RapidBoard.jspa?rapidView=184&modal=detail&selectedIssue=OY2-6538)
-This fixes the issue of question ids in a target not matching the answer.question id 
example:
BEFORE:
target:
"$..*[?(@.question=='_21PW-2021_-01')].rows[1].col6"
answer.question:
"question": "2021-21PW-01",
AFTER 
target:
"$..*[?(@.question=='2021-21PW-01')].rows[1].col6"
answer.question:
"question": "2021-21PW-01",
-some targets contained iquestiond and they were updated to question
=> fix target's question id and iquestiond to question

.github/PULL_REQUEST_TEMPLATE/prod-deployment.md, .github/PULL_REQUEST_TEMPLATE/standard.md, .github/PULL_REQUEST_TEMPLATE/val-deployment.md, .github/pull_request_template.md
modifying our pull request templates as a test for a potential workflow
=> modify pull request templates as a test

.github/CODEOWNERS
Slim down codeowners per discussion with team and new SDLC.
n/a
---
n/a
n/a
---
---
=> modify codeowners for seds

.github/PULL_REQUEST_TEMPLATE/test-to-val-deployment.md, .github/PULL_REQUEST_TEMPLATE/val-to-prod-deployment.md
Simple updates to PR template
n/a
---
n/a
n/a
---
---
=> pr template updates

README.md, destroy.sh
Adds destroy fix to SEDS
MDCT-2468
---
N/A
---
---
=> Add destroy fix to SEDS

.github/CODEOWNERS, .github/workflows/snyk-test.yml, .snyk, services/ui-src/src/components/Example/Example.js, services/ui-src/src/components/FormPage/FormPage.js, services/ui-src/src/components/FormTemplates/FormTemplates.js, services/ui-src/src/components/GenerateForms/GenerateForms.js, services/ui-src/src/components/GenerateTotals/GenerateTotals.js, services/ui-src/src/components/LoadData/LoadData.js
---
- Fix Alert Component (MDCT-2697)
=> dev -> val

.github/workflows/snyk-test.yml
Two workflow Jobs
Runs during PR creation on main and outputs the findings in GitHub Workflow console
Runs on Cron and creates JIRA ticket based on findings
JIRA ticket behavior
Existing ticket check is set to default 60days, this can be adjusted as needed.
The same Vulnerability can re-exist after the resolution when a the same package is added for this reason there is a check for Closed or Cancelled ticket and based on that a ticket get created.
SNYK Ignore
There is a .snyk file in the root directory that can hold a list of snyk ignore ids, a vulnerability can be manually added there following the same synaxt in the file, so when Snyk scan runs all the vulnerabilities in .snyk file will be ignored.
Important updates
Author checklist
I have performed a self-review of my code
I have added …
=> updated snyk custom action version

.github/workflows/git-secrets.yaml, .gitleaks.toml, .pre-commit-config.yaml, SECRETSCANNING.md
=> Implementing secret scanning tools Gitleaks and Precommit

destroy.sh
Copy over bucket item removing loop from MCR – noticed this error in CARTS but it could apply here if bucket item numbers got high enough
MDCT-2533 kinda
=> add fix from mcr to iterate over items

services/app-api/libs/dynamodb-lib.js, services/database/package.json, services/database/serverless.yml, services/database/yarn.lock
Switch dynamodb local dependencies
MDCT-2751
---
---
---
=> Switch dynamodb local dependencies

.github/workflows/schedule-jira-sync.yml
Same update as applied to [MCR](https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/11411)
Actions began working again after the update.
N/A
---
Proved in MCR
---
---
=> Sechub Sync - 1.0.3

.github/workflows/schedule-jira-sync.yml, .github/workflows/snyk-test.yml, services/app-api/libs/dynamodb-lib.js, services/database/package.json, services/database/serverless.yml, services/database/yarn.lock
---
- Switch DynamoDB local dependencies (MDCT-2751)
- Fix SecurityHub scan
=> test  → val

.github/workflows/snyk-test.yml
Description
Two workflow Jobs
Runs during PR creation on main and outputs the findings in GitHub Workflow console
Runs on Cron and creates JIRA ticket based on findings
Here is a sample JIRA output
https://qmacbis.atlassian.net/browse/MDCT-2579
JIRA ticket behavior
Exisitng ticket check is set to default 60days, this can be adjusted as needed.
The same Vulnerability can re-exist after the resoultion when a the same package is added for this reason there is acheck for Closed or Cancelled ticket and based on that a ticket get created.
SNYK Ignore
There is a .snyk file in the root directory that can hold a list of snyk ignore ids, a vulnerabiity can be manually added there following the same synaxt in the file, so when Snyk scan runs all the vulnerabilities in .snyk file will be ignored. …
=> updated action and added assignee

.github/workflows/scan_security-hub-jira-integration.yml, .github/workflows/scan_snyk-jira-integration.yml
The workflow wasn't running when we wanted it to, was erroneously assigning @BearHanded instead of @kx6z, and needed to have custom field selection IDs updated.
Changes made:
- Snyk & SecurityHub workflow cron jobs updated to run daily at 6am UTC.
- Auto-assignee is now Rehman instead of Brendan.
- Custom `Application` field selection ID is now correct for this app.
- Update workflow filenames to be more descriptive.
PS - Do you like this PR? If so, you're in luck -- there's a matching one in each repo for you to review and approve!
n/a
---
n/a
n/a
---
---
=> update security scan / jira integration workflows

README.md, services/ui-auth/handlers/createUsers.js, services/ui-auth/libs/cognito-lib.js, services/ui-auth/libs/users.json, services/ui-auth/package.json, services/ui-auth/serverless.yml, services/ui-auth/yarn.lock
Creates a set of test users, which will be initialized in every dev-based environment on deploy.
MDCT-2142
---
Try to log in with one of those users.
n/a
---
=> Add user bootstrapping

services/ui-auth/libs/users.json
Correct the group attribute for the admin user. This is already manually corrected in seds dev cognito and tested, reflecting in the seed doc.
MDCT-2142
---
---
---
=> [MDCT-2142] Admin Role Seed 

.github/workflows/scan_security-hub-jira-integration.yml
Updated security hub version from 1.0.3 to 1.0.5 and also added auto-assign to the user who is also assigned the snyk tickets
MDCT-
---
Verify new tickets are being assigned to user in Jira
Changed sechub workflow file to update version as well as add auto-assign
---
---
=> Implement sechub updates and Auto-assign

.github/workflows/deploy.yml, .github/workflows/scan_security-hub-jira-integration.yml, .github/workflows/scan_snyk-jira-integration.yml, .github/workflows/snyk-auto-merge.yml
updated Both snyk and security hub workflow configurations with Jira Enterprise values
---
---
=> updated to jira ent

services/ui-src/public/index.html, services/ui-src/src/components/App/App.js, services/ui-src/src/components/App/App.test.js, services/ui-src/src/utility-functions/tealium.js, services/ui/serverless.yml
Add tracking as described in ticket
CMDCT-3059
---
Testing handled by Blast team
---
---
=> Add tealium tracking to SEDS

services/ui-src/public/index.html
=> fix tealium domain (#14790)

README.md
Just some extra info in the readme about expected behavior with the providing IDP
N/A
---
---
---
=> Readme update: SAML Attribute clarification

.github/setBranchName.sh, destroy.sh
Found a small error that needs to be corrected
CMDCT-
---
---
---
=> Fix snykdependa destroy

services/ui-src/public/index.html, services/ui-src/src/utility-functions/tealium.js
=> CMDCT-3288.II: Tealium Fix

.github/setBranchName.sh, .github/workflows/deploy.yml, .github/workflows/destroy.yml, services/ui-auth/package.json, services/ui-auth/yarn.lock, services/ui-src/public/index.html, services/ui-src/src/utility-functions/tealium.js
---
- SSM parameter for Cognito Pools (CMDCT-3185)
- Use correct casing for env stage (CMDCT-3185)
- Allow API endpoints to use SSM vars (CMDCT-3185)
- Destroy fix (CMDCT-3218)
- Remove LoadData page (CMDCT-3224)
- Tealium environment variable fix (CMDCT-3288)
=> test → val

.github/workflows/deploy.yml
The change here are smaller than in the newer products, as there are not multiple test suites to produce artifact file collisions, but the same change have been introduced to improve consistency.  
CMDCT-3555
---
I pushed a build set to always upload artifacts.  The artifacts can be seen to be correctly publishing [here](https://github.com/Enterprise-CMCS/macpro-mdct-seds/actions/runs/8789118010).  A successful build will not produce artifacts.
---
---
---
=> Improve Artifact Upload

.github/workflows/scan_snyk-jira-integration.yml
* Creates tickets with major version update
=> update snyk version

.github/workflows/codeql-analysis.yml, .github/workflows/deploy.yml
The [code-climate action](https://github.com/paambaati/codeclimate-action) we use recently had an [upgrade to node 20](https://github.com/paambaati/codeclimate-action/issues/731). That was one of the lingering Node 16 actions across our apps so I'm taking this opportunity to bump actions across our apps.
CMDCT-3577
---
All actions pass and there are no warnings about Node 16 actions! 🎉 
No code changes
---
=> Bump action versions

services/ui/serverless.yml
=> Add header to cloudfront function

.github/workflows/deploy.yml, services/app-api/libs/kafka-source-lib.js, services/database/scripts/sync-kafka-2024.js, services/database/scripts/utils/dynamodb.js, services/output.sh
Writeup copied from [CARTS](https://github.com/Enterprise-CMCS/macpro-mdct-carts/pull/139639).
Breaking change in kafka-source-lib.
The updated AWS unmarshall utility function is processing the provided settings for wrapping numbers differently and resulting in messages to bigmac that have all numbers nested like so:
```
Message: 'New item!', Id: NumberValue { value: '101' } }
vs
{ Message: 'New item!', Id: 101 } 
```
We need it to look like that second format. ({ Message: 'New item!', Id: 101 }). To do that, looks like all we need to do is remove the optional unmarshal options. However, we also need to let all downstream listeners know that things have been updated. To that end, we have a script that we can run to look at all the reports in 2024, update their last synced time to the time …
=> [CMDCT-3674] Unmarhsall fix + deploy output

run, src/run.ts
- Remove pragma comments when running `./run update-env` or `./run local --update-env`.
---
1. Run `./run local --update-dev` to update your local .env and start SEDS
2. Verify there are no pragma comments in `.env`
3. Verify SEDS works as normal
4. Run `./run update-env` and verify there are no pragma comments in `.env`
=> Remove pragma comments with update-env

services/ui-src/.babelrc, services/ui-src/package.json, services/ui-src/yarn.lock, yarn.lock
Snyk identifies a few issues arising from these two plugins, remove the unused one and line up the second.
N/A
---
https://d3bh9qv4b1o0le.cloudfront.net/
this loads and unit tests pass
(you can't do anything but login in this env)
---
---
---
=> Align semver and remove unused babel cra plugin

deploy.sh, package.json, serverless-compose.yml, services/app-api/.gitignore, services/app-api/export/exportToExcel.js, services/app-api/handlers/form-templates/post/obtainFormTemplate.js, services/app-api/handlers/form-templates/post/obtainFormTemplateYears.js, services/app-api/handlers/form-templates/post/updateCreateFormTemplate.js, services/app-api/handlers/forms/get.js, services/app-api/handlers/forms/get/getFormTypes.js, services/app-api/handlers/forms/post/generateQuarterForms.js, services/app-api/handlers/forms/post/obtainAvailableForms.js, services/app-api/handlers/forms/post/obtainFormsList.js, services/app-api/handlers/forms/post/saveForm.js, services/app-api/handlers/state-forms/post/generateEnrollmentTotals.js, services/app-api/handlers/state-forms/post/updateStateForms.js, services/app-api/handlers/users/get/getUserById.js, services/app-api/handlers/users/get/listUsers.js, services/app-api/handlers/users/post/createUser.js, services/app-api/handlers/users/post/deleteUser.js, services/app-api/handlers/users/post/obtainUserByEmail.js, services/app-api/handlers/users/post/obtainUserByUsername.js, services/app-api/handlers/users/post/obtainUsernameBySub.js, services/app-api/handlers/users/post/updateUser.js, services/app-api/serverless.yml, services/ui-auth/serverless.yml, services/ui-src/serverless.yml, services/ui-waf-log-assoc/serverless.yml, services/ui/serverless.yml, yarn.lock
Deploy with [serverless compose](https://www.serverless.com/framework/docs/guides/compose)
- add serverless-compose.yml to define our services and their dependencies
- add `@serverless/compose` package
- remove warmup plugin
- update serverless invoke statements to use `aws lambda invoke` instead
- update variable references to use `params` from serverless instead of `cf:` outputs
- update deploy script to run from root, using serverless compose
| | w/o compose | with compose |
|----|----|-----|
| Clean deploy | 21:02 | 12:50 |
| Re-deploy no changes |  6:27  | 3:56 |
| Re-deploy no changes (2) | 19:39 (somehow?) | 3:53 |
| Re-deploy no changes (3) | 3:52 (somehow??) | 3:48 |
CMDCT-3586
---
No changes to app functionality or deployed env.
Compare deploy times in these test branches
Test …
=> Set up Serverless Compose

services/ui-src/src/components/Login/Login.jsx
Users get stuck in a loop if their token is expired when using the Okta login.
Reproducing the issue:
- SEDS refresh tokens are good for 30 days (questionable, should probably change to be in line with the other apps).
- To reproduce this in Dev I currently have it set for 1hr. Returning to that page after 1 hour reproduces the issue.
-I have only been able to reproduce it with Federated logins, because Cognito test user logins is a different auth flow.
We can't use EUA logins in dev branches
The cause:
I believe amplify 4 -> 5 causes the signout call to always navigate to the signout URL where that did not used to be the case (potentially?). When the most recent login with a federated login, the call exhibits this behavior, but not otherwise or on a user that has never logged in …
=> [MDCT-3745] Remove unnecessary logout call

services/app-api/libs/authorization.js
We have been seeing, across multiple environments (including prod) intermittent issues when navigating & performing actions around the site. The relevant error message seems to be this:
```
Error: Failed to fetch https://(...)/.well-known/jwks.json: write EPIPE
at ClientRequest.oe (.../services/app-api/node_modules/aws-jwt-verify/dist/esm/https-node.js:51:25
```
Although we have also seen "socket hang up" instead of "write EPIPE" for the reason, both mean roughly the same thing: the connection was closed from the other end.
Since this issue is intermittent, my best guess is a timeout issue. I don't like that as an explanation, since this should be an AWS lambda in us-east-1, talking to an official AWS service in us-east-1, which _ought_ to be very fast. Nevertheless, if increasing the …
=> Increase Cognito timeout to alleviate "socket hang up" issues

services/ui-src/yarn.lock
Flagged as vulnerability, letting yarn handle the updated version
N/A
---
---
---
---
=> Update elliptic version

services/ui-src/index.html
Per CMS requirements, we perform analytics with the 3rd-party service Tealium. Currently we load the Tealium script from a CDN, but CMS has decided to self-host the script instead. To make sure there are no surprises, they are phasing in this change one environment at a time.
This PR implements that change. In DEV only, we will begin loading Tealium from CMS' own servers.
Note that we actually load two Tealium scripts: one tiny synchronous script (utag.sync.js), and the main asynchronous one (utag.js). Previously our index.html page included three separate hardcoded script tags, to configure & load these two Tealium scripts dynamically. That's silly. I've condensed all of the Tealium-loading logic into one tag.
CMDCT-3955
---
There is very little we can do to test this on our end. What we …
=> Change tealium domain for DEV ONLY

services/ui-src/src/components/Users/Users.jsx, services/ui-src/src/components/Users/Users.test.jsx, services/ui-src/src/utility-functions/exportFunctions.js, services/ui-src/src/utility-functions/exportFunctions.test.js
On the user management page, SEDS supports the ability to export the full list of users to a file. Excel and PDF exports have been available for a long time. This PR adds a CSV option.
Why? CSVs are faster, can be viewed & edited with a huge variety of different applications, and do not require any special software packages to generate. This is in sharp contrast to Excel; the library we use to generate excel files directly has begun to raise security warnings. If our users are happy with the CSV option, then in the future we can retire the Excel export option and dismount the update treadmill.
Related to, but does not resolve: CMDCT-3851
---
1. Log in as `adminuser@test.com`
2. Go to the "View / Edit Users" page
3. Click the "CSV" button on top of the table
* Your browser should …
=> Add CSV export button to user table

services/app-api/package.json, services/app-api/yarn.lock, services/database/package.json, services/database/yarn.lock, services/ui-auth/package.json, services/ui-auth/yarn.lock
Routine maintenance. This PR will take the place of several PRs auto-generated by Synk, which would upgrade these packages piecemeal.
n/a
---
n/a - minor versions of aws-sdk packages do not contain breaking changes.
n/a
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~
- ~[ ] I have performed a self-review of my code~
---
- ~[ ] Product: This work has been reviewed and approved by product owner, if necessary~
- ~[ ] These changes are significant enough to require an update to the SIA.~
- ~[ ] These changes are …
=> Bump aws-sdk to 3.645.0

services/ui/serverless.yml
This domain is requested by one of our tealium scripts; if we want analytics to function, it needs to be allowed.
CMDCT-3955
---
---
---
---
=> Add another analytics-related domain to the CSP

services/database/utils/dynamodb.js
Add the missing logger keys to the dynamodb utility file
CMDCT-
---
1. Deploy the stack w/o errors (I had a debug error without this fix)
---
---
---
=> fix: resolve debug error and add missing logger keys

deployment/app.ts, deployment/constructs/cloudwatch-logs-resource-policy.ts, deployment/constructs/cloudwatch-to-s3.ts, deployment/constructs/lambda-dynamo-event.ts, deployment/deployment-config.ts, deployment/stacks/api.ts, deployment/stacks/customResourceRole.ts, deployment/stacks/data.ts, deployment/stacks/deployFrontend.ts, deployment/stacks/env-config.template.js, deployment/stacks/parent.ts, deployment/stacks/ui-auth.ts, deployment/stacks/ui.ts, deployment/utils/systems-manager.ts, services/database/handlers/seed/tables.js, src/run.ts, src/write-ui-env-file.ts
This branch started with updating the CDK to incorporate the react frontend build and deployment into the CDK deployment rather than being accompanied via a wrapper script that ran with the deployment.  But... then due to the holidays and not wanting to create a PR during that time... I kept working on the same branch so it grew and it also has changes to:
1. Stop getting SSM parameters throughout the deployment process and just get them all at the beginning, that avoids any of the deployment functions ever needing to be async (CDK doesn't like that).
2. Added a construct specifically for lambda functions that are to subscribe to dynamodb event streams.
3. Leverage AWS CDK custom resources to invoke our bootstrap users and seed data functions, that's the CDK way to do it.
4. Improving the …
=> Improvements to CDK project - frontend deployment and various others

services/app-api/package.json, services/app-api/yarn.lock, services/database/package.json, services/database/yarn.lock, services/ui-auth/package.json, services/ui-auth/yarn.lock
=> Bump AWS SDK version numbers to 3.709.0

services/ui-src/src/components/Users/Users.jsx
=> Fix user state display some more

deployment/constructs/cloudwatch-logs-resource-policy.ts, deployment/constructs/cloudwatch-to-s3.ts, deployment/deployment-config.ts, deployment/stacks/api.ts
isDev is to avoid resources being deployed too many times in an account, since we're not deploying main/master yet this resulted in these resources not being deployed at all.  This change is to fix that.
CMDCT-
---
---
---
---
=> CDK fix CloudWatch resource policy

deployment/constructs/dynamodb-table.ts, deployment/deployment-config.ts, deployment/stacks/api.ts, deployment/stacks/data.ts, deployment/stacks/parent.ts, deployment/stacks/ui.ts
This is an attempt to make reasonable choices about what to retain (and if we do, I made sure names wouldn't clash with sls retained resources).
CMDCT-4223
---
1) Deploy cdk stack
2) Destroy stack
3) Verify that retained resources are still there
There are a couple other small tweaks here (including master in isDev's logic) and a few other things like renaming log buckets in the cloudformation so that it is easier to tell what is what. Removing retention policies or versioning from places where it doesn't seem to make sense.
---
---
---
_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → …
=> CMDCT-4223 makes an attempt at retaining resources based on isDev

services/app-api/serverless.yml, services/ui-waflog-s3-bucket/serverless.yml, services/ui/serverless.yml
This is an attempt to make reasonable choices about what to retain (and if we do, I made sure names wouldn't clash with cdk created resources).
CMDCT-4223
---
1) Deploy sls stack
2) Destroy stack
3) Verify that retained resources are still there
NA
---
---
---
=> CMDCT-4223 making sure important logs are retained

services/app-api/libs/authorization.js
This is a problem that has lingered since serverless v4 was implemented for SEDS
CMDCT-4294
---
Login successfully to the app here: https://d2igl8afmosgpr.cloudfront.net/login
NA
---
---
---
=> CMDCT-4292 - fixes authorization jwtDecode

deployment/import_instructions.md
Added to import checklist to be sure that Okta is working before considering the new cdk setup totally functional.
CMDCT-4108
---
NA
NA
---
---
---
=> CMDCT-4108 update to import instructions to verify EUA login works

deployment/stacks/deployFrontend.ts, deployment/stacks/env-config.template.js
A series of events occured on jon-cdk that resulted in the env-config.js being deleted and not being replaced as it wasn't seen as new, so this PR is adding a timestamp to env-config.js to ensure the config gets pushed on every deployment
---
---
---
---
=> Add timestamp to env-config.js to ensure the config gets pushed on every deployment

deployment/app.ts, deployment/prerequisites.ts, src/run.ts
Move CDK DefaultStackSynthesizer from secrets manager to CDK code
CMDCT-4330
---
---
---
---
=> Move CDK DefaultStackSynthesizer from secrets manager to CDK code

.env.tpl, deployment/stacks/api.ts, services/app-api/handlers/form-templates/post/obtainFormTemplate.js, services/app-api/handlers/form-templates/post/obtainFormTemplateYears.js, services/app-api/handlers/form-templates/post/updateCreateFormTemplate.js, services/app-api/handlers/forms/get.js, services/app-api/handlers/forms/get/getFormTypes.js, services/app-api/handlers/forms/post/generateQuarterForms.js, services/app-api/handlers/forms/post/obtainAvailableForms.js, services/app-api/handlers/forms/post/obtainFormsList.js, services/app-api/handlers/forms/post/saveForm.js, services/app-api/handlers/kafka/get/forceKafkaSync.js, services/app-api/handlers/notification/uncertified.js, services/app-api/handlers/shared/sharedFunctions.js, services/app-api/handlers/state-forms/post/generateEnrollmentTotals.js, services/app-api/handlers/state-forms/post/updateStateForms.js, services/app-api/handlers/users/get/getUserById.js, services/app-api/handlers/users/get/listUsers.js, services/app-api/handlers/users/post/createUser.js, services/app-api/handlers/users/post/deleteUser.js, services/app-api/handlers/users/post/obtainUserByEmail.js, services/app-api/handlers/users/post/obtainUserByUsername.js, services/app-api/handlers/users/post/obtainUsernameBySub.js, services/app-api/handlers/users/post/updateUser.js, services/database/scripts/removeActiveFlagFromUserObject.js
This PR standardizes the way we use env variables to access dynamo tables
CMDCT-4328
---
Run app! It should still work :)
NA
---
---
---
=> CMDCT-4328 - standardizes the way we use env variables to access dynamo tables

.github/workflows/scan_security-hub-jira-integration.yml
Old ubuntu being retired. Let's get the latest version!
CMDCT-4332
---
Run the Github Action once it's merged like so:
NA
---
---
---
=> CMDCT-4332 upgrading ubuntu for security hub jira integration

package.json, services/app-api/handlers/forms/post/saveForm.js, services/app-api/handlers/kafka/get/forceKafkaSync.js, services/app-api/handlers/kafka/get/forceKafkaSync.test.js, services/app-api/package.json, services/app-api/yarn.lock, services/database/package.json, services/stream-functions/package.json, services/ui-auth/package.json, services/ui-src/package.json, services/ui-src/yarn.lock, services/ui-waf-log-assoc/yarn.lock, services/ui-waflog-s3-bucket/yarn.lock, services/ui/package.json, yarn.lock
We still pull it in as a transient dependency for various reasons, but we have no need of it ourselves.
n/a
---
There should be no changed behavior. Wait for the end to end tests to pass. lol.
n/a
---
- ~[x] I have performed a self-review of my code~
---
- ~[ ] Product: This work has been reviewed and approved by product owner, if necessary~
- ~[ ] These changes are significant enough to require an update to the SIA.~
- ~[ ] These changes are significant enough to require a penetration test.~
=> Remove direct Lodash dependencies from SEDS

deployment/IMPORT_INSTRUCTIONS.md, deployment/local/README.md, package.json, run, src/run.ts, yarn.lock
Updates docs and introduces colima
CMDCT-4337
---
Try to follow instructions here: https://github.com/Enterprise-CMCS/macpro-mdct-seds/blob/cmdct-4337/deployment/local/README.md
NA
---
---
---
=> CMDCT-4337 - adds colima for docker for localstack + updating documentation

services/app-api/serverless.yml, src/getCloudformationTemplateForStage.ts, src/run.ts
Needed to be 1000% sure we aren't deleting things we need.
CMDCT-4238
---
NA
NA
---
---
---
=> CMDCT-4238 - recreating destroy of nonretained resources protection

deployment/stacks/parent.ts
=> fix for deploy of cdk

deployment/stacks/ui-auth.ts
solving CDK cognito issue 2
CMDCT-
---
---
---
---
=> solving CDK cognito issue 2

deployment/deployment-config.ts, deployment/stacks/parent.ts, deployment/stacks/ui-auth.ts
=> more fixes for secureCloudfrontUrl

deployment/app.ts, deployment/constructs/dynamodb-table.ts, deployment/constructs/waf.ts, deployment/deployment-config.ts, deployment/local/prerequisites.ts, deployment/stacks/api.ts, deployment/stacks/data.ts, deployment/stacks/deployFrontend.ts, deployment/stacks/parent.ts, deployment/stacks/ui-auth.ts, deployment/stacks/ui.ts, deployment/utils/misc.ts, deployment/utils/vpc.ts
Refactor of parent.ts and formatting of the deployment directory files.
CMDCT-4443
---
---
---
---
=> Suggested Changes to CMDCT-4443 PR

deployment/constructs/lambda-dynamo-event.ts, deployment/constructs/lambda.ts, deployment/stacks/data.ts, deployment/stacks/ui-auth.ts
add forceDockerBundling to esbuild bundling
CMDCT-
---
---
---
---
=> add forceDockerBundling: true to esbuild config

.github/workflows/update-code-json.yml
Removing tiny id overspecification that doesn't match standardized way of doing update-code-json.yml
=> CMDCT-4930 tidying up

services/app-api/libs/dynamodb-lib.js, src/run.ts
Run local stopped working for unexplained reasons. This should fix it so that we can use Dynamo locally without errors. (They manifested as 502 for our own api calls to the back end)
CMDCT-4935
---
Open app and look through console. Make sure things like user/banner/reports load.
NA
---
---
---
=> CMDCT-4935 - getting run local to work again

.github/setBranchName.sh, deployment/MASTER_TO_MAIN_INSTRUCTIONS.md, deployment/app.ts, deployment/deployment-config.ts, deployment/stacks/api.ts, deployment/stacks/deployFrontend.ts, deployment/stacks/empty/parent.ts, deployment/stacks/env-config.template.js, deployment/stacks/imports_included/data.ts, deployment/stacks/imports_included/parent.ts, deployment/stacks/imports_included/ui-auth.ts, deployment/stacks/imports_included/ui.ts, deployment/stacks/parent.ts, deployment/stacks/ui-auth.ts, deployment/stacks/ui.ts, services/app-api/libs/kafka-source-lib.js, services/app-api/setupTests.js
Many updates to allow nearly all names of master to become main
CMDCT-5011
---
Make sure the app still works after the transition
NA
---
---
---
=> CMDCT-5011 - remove most remaining vestiges of master

services/ui-src/index.html
Tealium tracking hasn't been working as expected. This PR updates the Tealium path following documentation [here](https://confluence.cms.gov/spaces/BLSTANALYT/pages/432352891/Tealium+Implementation+Documentation+for+Single-Page+Applications). Once we've confirmed with BlastX that they are seeing the expected analytics data in Adobe then we can move forward with making the same changes across all apps.
CMDCT-5066
---
Once merged, will set up a meeting with BlastX to test
=> [SEDS] Update Tealium path
