Enterprise-CMCS/macpro-mdct-seds

- services/database/serverless.yml
The original PR to seed the database with tables merged but received an error described here: https://github.com/CMSgov/cms-mdct-seds/actions/runs/466967156
This PR is attempting the resolution described here: https://github.com/davidgf/serverless-plugin-canary-deployments/issues/38
"The versionFunctions serverless parameter was set to false because we ran out of lambda storage and we weren't really rolling back using the versions anyway.
So, if anyone else runs into this problem, it could be that function versioning is off. Turning it back on would fix it."
From @sethsacher: "Best thing coming up is versionFunctions is set to false and should be set to true instead. We aren’t explicitly setting it to false, so perhaps this is occurring."
For placement, I referenced this: …
> add versionFunctions to serverless.yml

- services/database/serverless.yml
Error Message
XXXXXXXX - CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename xxxxxx-dev and update the stack again.
Problem
You’ve made some changes to a resource, and CloudFormation needs to replace the resource by removing and recreating it. However, CloudFormation cannot replace a resource that has a custom name.
Solution
To get around this limitation, you have to rename the resource in your serverless.yml, deploy it, and rename it back.
Let’s say the resource is called usersTable-dev, rename it to usersTable2-dev and deploy.
After the deployment succeeds, you can rename the resource back to usersTable-dev and continue deploying.
Important: If the resource you are renaming is a DynamoDB table, renaming it will drop all the data. Make sure to …
> change structure of all tables to be 1 attribute per table (part 1 of fix)

- services/ui-src/src/Routes.js
Unauthenticated routes ONLY work is the user is logged out. All routes have been updated to account for this.
> Switch unauthenticated routes to authenticated, where applicapable

- services/app-api/serverless.yml
Previously, serverless was trying to reach out to cloud flair on the local environments. This will not work. The fix is to add environment variables to define the names and allowing a fallback to cloudfront for other environments (val, dev, prod).
> Bugfix: Update table definitions to use ENV first, then CF

- services/app-api/serverless.yml
So we don't run into this issue if we try to scan any other tables that exist:
- AuthUserRolesTableArn
- AuthJobCodesTableArn
- AuthUserStatesTableArn
> add the other table ARNs to LambdaApoRole

- services/app-api/handlers/create.js
- services/app-api/handlers/delete.js
- services/app-api/handlers/get.js
- services/app-api/handlers/list.js
- services/app-api/handlers/update.js
changed these unnecessarily while trying to resolve 500 error on Users api - changing them back now
> Revert tableName variable naming in generic api handlers

- README.md
**Linked Issue:**
None, this came about after a group discussion with the dev team. 
**Overview:**
We decided to structure our handlers in such a way that each folder names a _type_ of API and the files within it correspond to an HTTP verb and contain only one function. This was done so that our handlers dont become confusing as our API grows. Previously similar/related handlers were together in folders (ie: get-single-form and get-list-of-forms), but as the need for more verbs grows folders like that could quickly become messy. The solution we reached was to give handlers such as those their own folders and the only thing each folder would contain is files named after HTTP verbs, each with only one function (called main). 
**Files changed (1):**
`README.md`
The README has been updated to …
> Feature: Add handler organizing convention to the README

- README.md
The purpose of this PR is to add in a maintainability build badge to the cms-mdct-seds repository. The badge is located within the README.md and is pointing to the main integration branch which is master. Clicking on the badge itself will take an individual out to code climate in which they can investigate all identified issues. 
For more on code climate maintainability please reference :
https://docs.codeclimate.com/docs/maintainability
> Skipci add code climate badge

- services/ui-src/src/components/form/FormPage.js
- services/ui-src/src/containers/Quarterly.js
Replaces PR #168 
Developer: Alexis Woodbury
Linked Issue:
None, hotfix.
Overview:
The router on the quarterly page was not providing the correct URL and was missing 21PW. Form page added an additional step to formatting.
Files Changed (2):
services/ui-src/src/components/form/FormPage.js
Form page can now take in a URL with hyphens and replaces them with periods. Its best for the URL segments to not have periods in them so they're being sent from Quarterly.js as "/forms/AL/2021/1/64-21E". Form page is replacing the hyphen in the URL with a period before fetching the form.
services/ui-src/src/containers/Quarterly.js
21PW is added to the list of possible forms. 64-21ei removed because that form doesnt exist.
All url segments have been formatted to match form names except that instead of …
> Hotfix quarterly router

- services/ui-src/src/App.js
Roles was previously checking with an includes check, which failed if role is null. This checks for null first.
> Correct logic when checking for roles

- services/database/serverless.yml
PITR was missing on a few tables and recently started alerting in sechub. Turn on the setting.
Just a few lines in serverless.yaml definitions
https://qmacbis.atlassian.net/browse/MDCT-2315
Check the deployed branch's settings
N/A
> [MDCT-2315] Enable PITR on all tables

- scripts/pitr_recovery.py
Quick python script in the same manner as the other saved SEDS data correction scripts, but way less complicated.
Just takes a list of source and destination tables, and copies the entries from one into the other with a batch request.
Instructions for running are included in the script comments
MDCT-2395
---
This has been run in dev already against the recovery tables, but feel free to follow the script instructions and set up the aws credentials file before running.
---
---
> [MDCT-2395] Data Recovery Script

- services/app-api/handlers/forms/post/obtainAvailableForms.js
- services/app-api/handlers/shared/sharedFunctions.js
- services/app-api/libs/dynamodb-lib.js
Update the scan to consider last evaluated.
Removed a dangerous recursive one that tracked with a global list of items.
I'm on the fence as to whether or not the recursive search should be opt-in or just for all, but I think this bug proves that not having default for all can get devs into some risky spots. Future improvement might be to make the scan optionally opt-out of recursive search, but I have no use case for it at the moment.
You should see this when you try to create existing data now:
MDCT-2400
---
Pull it down, and interact with the app. Nothing should break. Generate a lot of forms (2.5MB). You shouldn't be able to overwrite existing data.
---
---
_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → …
> Force scan to consider last evaluated, and remove dangerous alternative

- services/ui-src/src/components/SynthesizedGrid/SynthesizedGrid.js
Question 5 for 64.21 was having some wild calculation issues. Turns out adding strings and numbers are 2 very different things.
MDCT-481, MDCT-2390
---
Load up 64.21E. Fill some numbers out, see it gives the expected answer!
---
---
> Ensure data from DB returns as a number to be calculated on

- services/app-api/handlers/forms/post/generateQuarterForms.js
When generateQuarterForms is called automatically on the first day of each quarter, it must generate forms for the _previous_ three months. This PR fixes an off-by-one error in that calculation.
MDCT-2180
---
Wait until July 1st and see what happens? I isolated the math into a function, and tested that function locally with this suite. I didn't commit these tests today; I think setting up unit testing for SEDS would be out-of-scope for this ticket.
n/a
---
> Adjust the date math in generateQuarterForms.js

- services/ui-src/src/components/Example/Example.js
- services/ui-src/src/components/FormPage/FormPage.js
- services/ui-src/src/components/FormTemplates/FormTemplates.js
- services/ui-src/src/components/GenerateForms/GenerateForms.js
- services/ui-src/src/components/GenerateTotals/GenerateTotals.js
- services/ui-src/src/components/LoadData/LoadData.js
USWDS Alert component requires headingLevel, and will fail to render on the page if one is not provided. This PR provides the arg to all components.
Notably, this was causing Saving, and Submission to lead to a blank page in deployed environments.
MDCT-2697
---
* Log in as a state user
* Navigate to a form
* Save, see the alert. (This would error before)
* Submit and certify successfully. (This would error before)
---
---
> [MDCT-2697] Fix blank pages on Save or Submit. USWDS component required arg.

- scripts/form_answer_scan.py
- services/ui-src/src/components/FormLoadError/FormLoadError.js
- services/ui-src/src/components/FormLoadError/FormLoadError.test.js
- services/ui-src/src/components/FormPage/FormPage.js
- services/ui-src/src/components/NotApplicable/NotApplicable.js
- services/ui-src/src/components/Quarterly/Quarterly.js
- services/ui-src/src/store/reducers/singleForm/singleForm.js
- services/ui-src/src/store/reducers/singleForm/singleForm.test.js
SEDS Help Desk Issues:
- All 64.ECI
- Some 2019/2020 forms. A txt file with the missing items has been attached to the relevant ticket in JIRA. Many of these are part of the legacy import.
Changes:
- When viewing quarterly, ECI forms should no longer appear in the list
- If a user does manage to view a form without answer entries in the table, displays an error recommending they contact the help desk.
- Also includes a script for generating the list of missing items, not deployed, just a useful snippet.
USWDS Slider Component is ignoring onChange despite documentation listing it. OnInput() works. I have questions about if there's a more appropriate component to use for a toggle, but it works now if you click on the opposite side of the toggle.
MDCT-2742
MDCT-2743
---
- Run SEDS locally, …
> [MDCT-2742] [MDCT-2743] Missing Answers (64.ECI & 2019/2020 data)

- destroy.sh
Destroy script didn't get all resources, and often failed on some stack deletions
- Create your own branch and let it deploy
- Run this script locally and ensure everything deletes as expected
- Open Kion
- Get short-term access tokens for SEDS dev (MDCT dev account) and paste them in your terminal
- From SEDS root execute `./destroy {branch name here}`
- Once it lists all resources, repaste your branch name to start the destroy
- Make sure script does not error
- Also can track resources in AWS to make sure they go away...
Where to look
- Cloudformation
- Search for your branch name and see stacks get removed (app-api and ui take the longest)
- Make sure they actually get status "Delete completed" (or something like that), and not fail to delete
- Api Gateway
- Click on any api gateway …
> Update destroy script to cleanup hanging resources, and delete correctly

- services/app-api/handlers/forms/post/generateQuarterForms.js
- services/app-api/handlers/shared/sharedFunctions.js
- services/app-api/libs/dynamodb-lib.js
- services/app-api/serverless.yml
Adds an optional flag to generateQuarterForms to allow the process to look for forms missing answers. See MDCT-2841 and related tickets on more details around which entries are missing.
This parameter is able to be invoked in the lambda but is not added to the UI admin panel, due to the process running longer than the API Gateway timeout when looking for the reports to correct (about 89s).
Logging is added to show how many state forms, and how many answers are created in the process, a message if nothing new was needed, and individually logging out any answers created by the process that were missing.
The plan will be to back up the answer and state form tables and run the process with the flag.
MDCT-2841
MDCT-2649
---
- Pull the branch down
- As an admin, Generate as many quarters as you …
> [MDCT-2841] Add optional param to lambda to regenerate missing answers per quarter

- scripts/correct_templated_year.py
- scripts/form_answer_scan.py
- services/app-api/handlers/forms/post/generateQuarterForms.js
PR contains 3 files, broken down below.
The id's in the state forms are with `.` not `-`, and this change reflects that.
Question Table entry:
```json
{
"question": "2020-64.21E-01",
"column_total": true,
"created_by": "seed",
"created_date": "2020-01-15T12:46:35.838Z",
"form": "64.21E",
...
}
```
The generation script pulls the `64.21E` out of the question ID, and tries to key off it in the switch statement, but misses, never finds age ranges, and never generates answers for the user.
---
Based heavily on the null correction script, this addresses an issue in environments where the "targets" in question 5 are referencing IDs with the wrong year. The templates in those environments were long since corrected, but the outdated entries in the questions table still track 2021 for 2020 and …
> [MDCT-2841] SEDS Generate Answers - Correct ID in script + Targets Question -05 fix

- .github/workflows/dependabot-auto-merge.yml
- .github/workflows/deploy.yml
- .github/workflows/destroy.yml
- .github/workflows/git-secrets.yaml
- .github/workflows/scan_security-hub-jira-integration.yml
- .github/workflows/scan_snyk-jira-integration.yml
Updating versions to avoid warnings and deprecations
Note: these have already been tested in [another PR](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/1982) and I'm migrating them here
DOCS:
[aws-configure-credentials readme](https://github.com/aws-actions/configure-aws-credentials) – no breaking changes between 1 and 4. ("By default, your account ID will not be masked in workflow logs. This was changed from being masked by default in the previous version. AWS does not consider account IDs as sensitive information, so this change reflects that stance." Let me know if you want to mask this still and I'll add that option)
[cache readme](https://github.com/actions/cache) – no breaking changes with v3
[codeclimate action changelog](https://github.com/paambaati/codeclimate-action/rel …
> update action versions

- services/ui-src/package.json
- services/ui-src/yarn.lock
This PR bumps the version of the `uswds` package. The previous version had a vulnerability. A few notes:
* This app uses `@trussworks/react-uswds` rather than `uswds` directly, mostly. It is unlikely we had any exposure to the vulnerability.
* This app _does_ include some CSS from `uswds` directly. This seems redundant; surely the `@trussworks` package includes all relevant CSS already? But I believe that proving this would be difficult.
* The `uswds` package is not namespaced, but there does exist a namespaced version: `@uswds/uswds`. Possibly the latter is meant to supersede the former? Perhaps if we are upgrading packages we should be switching to the namespaced version? But I'm not 100% sure that's the case. And in any case, I would prefer to remove this dependency altogether, so that …
> Upgrade uswds to 2.14

- services/ui/serverless.yml
This PR adds several HTTP headers when serving the website:
* One which instructs browsers _only_ to interact with us via HTTPS
* One which instructs browsers not to serve our content within an iframe
The structure of the function to add these headers is identical to that of our other 4 apps: CARTS, QMR, MCR, MFP
CMDCT-271, CMDCT-308
---
We don't use iframes to serve this website, so this PR shouldn't change anything. A quick smoke test (as provided by Cypress) should be sufficient.
It will also be good to inspect the network tab when loading the site for the first time. The new headers should be present on the response.
n/a
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~
> Add security headers

- .github/workflows/deploy.yml
This PR will be identical for all repositories.
MACPRO took an approach of relaying all Snyk generated builds into a single ephemeral environment.  This is accomplished by setting the number of PRs Snyk can create outstanding to be one per project, and by setting a concurrency group in GHA workflow to ensure only one Synk build can occur at a time.  This makes sense for keeping infrastructure costs down, but it creates the situation where builds don't match the health of the environment, such that a successful build after a failed one will rectify the environment.  This is probably not much of a concern, but it's worth pointing out they are using OpenSearch and significantly more expensive infrastructure, and that limiting the creation of Snyk generated branches is only applicable at a …
> Fix comparison logic and snyk stage naming conventions

- destroy.sh
When a branch is deleted, the destroy action is triggered and the latest commit on the default branch, in this case `master` is used to execute the destroy action.  In order to test that I can force a destroy action to fail, I need to actually execute the destroy action against the changed code.  This essentially means I have to get this PR merged into master before I can test this code.  It's definitely not ideal, but it's a very minor change.  Once this is done, I can verify that failures to match will indeed fail, and then I can finish the rest of the work to extract the branch name setting logic and verify the action can successfully match dependabot and snyk generated branches against their interpolated stage names.
Note, this will not close the related ticket, but is the first step …
> Fail destroy action if no infrastructure is found for given stage

- .github/setBranchName.sh
- .github/workflows/deploy.yml
- .github/workflows/destroy.yml
- destroy.sh
This PR fixes two specific issues:
1. The Snyk integration implemented a change which was applied to the deploy action, which shortens auto-generated branches to a consumable length.  Dependabot already had a case in place to do this, but the change altered how Dependabot branches were interpolated into stage names, thus breaking the ability of the destroy action to correctly match infrastructure with a branch.  This caused infrastructure to leak.
2. Destroy actions did not fail when no infrastructure was identified.  Therefore successfully executed destroy actions did not indicate whether or not the action successfully destroyed the associated infrastructure.
There is a bit of a conundrum with this PR, in that it can't be tested in full until it's merged into master.   This is because …
> Fix snykdependa destroy

- services/ui-auth/serverless.yml
Exports the user pool info as a param the same way our other apps do. `authorization.ts` is already expecting this format, once this is deployed the dev env should pick it up.
[CMDCT-3185](https://jiraent.cms.gov/browse/CMDCT-3185)
---
This deployment shouldn't crash and burn and should resolve master after merging. The expected ssm params should appear in aws console.
---
---
> CMDCT-3185 - SSM Param for Cognito Pools

- services/app-api/libs/authorization.js
Use the `process.env.STAGE` casing that is used elsewhere (kafka-lib).
CMDCT-3185
---
---
---
> MDCT-3185 - Use correct casing for env stage

- services/app-api/libs/authorization.js
- services/app-api/libs/kafka-source-lib.js
- services/app-api/serverless.yml
Allow API endpoints to use SSM vars, this is used for getting the user pool info to verify a jwt.
CMDCT-3185
---
---
---
> CMDCT-3185 - Allow API endpoints to use SSM vars

- services/app-api/serverless.yml
- services/ui-src/src/components/CertificationTab/CertificationTab.js
Disabling the email notification flows for when a user uncertifies a report.
NOTE: As part of this ticket, the BOs have requested that these flows can be re-enabled, which is why it's being commented out as opposed to removed completely.
CMDCT-3335
---
N/A
---
---
> CMDCT-3335: Disable Email Notifications for Uncertification

- .github/branchNameValidation.sh
Lower char limit as dervived names cannot exceed 64 chars.  This doesn't account for that limit, but snyk branches can be as long as 59 chars and they are interpolated during deployment so if this script is also used for part of a git hook, we would still want to be able to manually manipulate synk branches.
The original change for this ticket was merged before discovering the lower limit, so the rest of the applications have the new lower limit but this app needs to be adjusted to remain consistently configured.
CMDCT-3222
---
---
---
> Lower char limit as dervived names cannot exceed 64 chars

- services/ui-src/public/index.html
- services/ui-src/src/components/App/App.js
- services/ui-src/src/utility-functions/tealium.js
Update the logic around when to make tealium page view calls.
- The page would sometimes not report at all at /login. Race condition with retrieving and attaching the tealium script. Add simple retry logic X times to see if the script is attached, otherwise bail.
- The page double reported when logged in. The hook needs to only fire once loading the user permisions into memory settles. 
- Some extra logic to not double report the /login page on redirect from /
- Corrects the url param used when in production from `production` to `prod`. This is not the same as the site_environment flag, and the two have been flipped back and forth together in the past.
CMDCT-3440
---
- Add breakpoints to the tealium library, or the calls in tealium.js before the call goes out in `window.utag.view`, OR add …
> [CMDCT-3440] Tealium Fixes

- .github/audit-account.sh
- .github/workflows/audit-account.yml
This PR applies a scheduled infrastructure audit to this application which can be manually executed or be run on a cron.  For more information, see [this PR](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2148)
CMDCT-3475
---
---
---
> Add workflow that creates scheduled job to audit AWS account

- services/ui/serverless.yml
Navigating to a path other than root returns a 403, and returns the index.html from the s3 bucket, while still preserving path. This allows the react routing to pick up the path and judge what should render, however, it is noisy and adds confusion to the mix about what is actually an error on the page.
After merging validate login with IDM and other features continue to work.
N/A
---
---
---
> CF Custom Response

- services/ui-src/package.json
Moving Dev dependencies into dev dependencies, not used while running.
Noticed one in a snyk PR as vulnerable but
- They aren't used when running
- Upgrade is dependent on the next node version.
We can at least put them in the right spot.
N/A
---
Can still run and test locally, and actions run.
---
---
> Shift Dev Dependencies

- services/app-api/libs/kafka-source-lib.js
We create Kafka messages from AWS event streams, which can be triggered by activity in DynamoDB. Usually, the event contains both a "before" and "after" of the object - but when the event is an insert, there is no "before". That is, `event.Records[n].dynamodb.OldImage` will be `undefined`. Unless we account for this, it will cause an error when we attempt to unmarshall it.
This is a low-impact bug; subsequent updates to that record will go through just fine, because they will have an OldImage. This PR just cleans up the initial edge case.
CMDCT-3431
---
🤷‍♂️  I guess we just merge it, and then watch the logs from our postKafkaData lambda?
n/a
---
--- …
> Allow for undefined OldImage in Dynamo stream events

- package.json
- run
- services/app-api/serverless.yml
- src/run.ts
- yarn.lock
It was noticed after the destroy action modifications, that AwsApiGateway Client Certificates were leaking and not being cleaned up.  Our previous destroy script had a specific action item to clean these certificates up, but because they had been leaking, the quota was overrun which was causing deployment issues.  
The initial effort to resolve included exploring the following:
- modifying the serverless stage destroyer to clean up certs;  this was abandonded when it was found that certs are not tagged and would have to be collected by namespace
- adding a custom resource that would be triggered by a Cloudformation stack event to clean them up
But after additional digging, it was appearing that the plugin used to manage the certs was in fact causing leaks, as each ephem would have two …
> Remove client certificates and fix run script

- services/ui/serverless.yml
When we added Tealium we added CSP headers :tada:
When we added CSP headers we forgot some style sheets in them 😢 
We can add those external style sheets to the CSP headers 🎉 
CMDCT-
---
[Deployed env](https://d13rvp0vtxl6kw.cloudfront.net/#/login) styles looks better than https://mdctsedsdev.cms.gov.
No CSP errors for font or style in the console.
There's still one for a tracking script but I am not sure we have intentionally added that. There used to be 50+ for fonts.
---
---
---
> Resolve missing seds styles when deployed

- services/app-api/handlers/forms/post/generateQuarterForms.js
- services/app-api/handlers/kafka/get/forceKafkaSync.js
- services/app-api/handlers/shared/sharedFunctions.js
- services/app-api/handlers/state-forms/post/generateEnrollmentTotals.js
2024 Q3 Forms should have gone out at the start of the month. The logs return that `batchWrite` is not a funciton. The naming got misaligned during the AWS SDK upgrade in our custom lib. The formatting of those commands is still correct.
Tested locally
CMDCT-3819
---
- Run locally
- Login as admin
- Use the Generate Quarters functionality for the next available quarter (q1 2022, I believe)
- Check that quarter released to the user.
---
---
---
> [CMDCT-3819] Generate Quarters Fix

- services/ui-src/src/components/Routes/Routes.jsx
- services/ui-src/src/index.jsx
This PR is to update SEDS from using `HashRouter` to `BrowserRouter`. The only thing this changes is that it removes the `#` from the url path. So instead of an url like `https://mdctsedsdev.cms.gov/#/forms/NC/2021/3`, it will now be `https://mdctsedsdev.cms.gov/forms/NC/2021/3` without the hash path. The routing functionality will still be the exact same. If users happen to have old urls saved with the hash in it, the router will properly route to the correct url without a hash.
On a side note, SEDS has an issue where when you log in with EUA login, it loads a blank page upon successful login. Unfortunately, this behavior is not re-createable locally because we can't do EUA logins locally so we're hoping to merge this to dev and see if it resolves that issue (my theory with that issue is …
> CMDCT-3726: experiment to update router to fix routing in seds

- services/data-deployment/serverless.yml
- services/data-deployment/yarn.lock
- src/run.ts
Note: The seed runner is currently not run in any environment. This PR purely fixes it such that it will not be a problem if we choose to use it in the future.
Test the conditionally-run seed command and fix issues with it so that it is ready to use when we want
CMDCT-3645 continued
---
See the logs from the [first run](https://github.com/Enterprise-CMCS/macpro-mdct-seds/actions/runs/9979698828/job/27579367733) and verify that the seed script failed
Verify it then succeeds in [this run](https://github.com/Enterprise-CMCS/macpro-mdct-seds/actions/runs/9980341512/job/27581482844), once the seed command was moved to `run` and re-ordered
Note: the latest build will not run seed because the `if` logic will be reinstated.
This branch changed the logic to ensure the data seed flow triggered. …
> Fix seed runner (for future use)

- services/ui-src/src/components/NotApplicable/NotApplicable.jsx
This PR addresses a cosmetic glitch that caused the "Not Applicable" toggle on every form page to be switched on, regardless of the form data's actual state.
That is: even when the form was Applicable (and the "Active" label on the left side was correctly bolded), the slider would show on the right ("Not Applicable") side on initial page load.
CMDCT-
---
1. Log in as a state user
2. Navigate to any editable form (that is, a form that has not already been certified)
* Note that the "Does this form apply to your state" toggle is on the left side, and **Active** is bolded
3. Click the toggle, and confirm that you want to lose all the data on the page
* Note that the toggle is on the right side, and **Not Applicable** is bolded
4. Refresh the page
* Note that the toggle and bolding have not …
> Set the Not Applicable toggle to the correct position on page load

- .github/workflows/audit-account.yml
In the audit workflow, a failing first conditional produces an exit code of 1 which will cause the job to fail if it's last in line.  This has never happened, because the only step that would produce no results is ci_inactive and is not last.  This change fixes all cases regardless of execution order.  This is a tangental task for operations, does not affect the application nor the CI process, so I'm going to up my YOLO badge.
None, found during dev elsewhere.
---
---
---
---
> Add or statement to prevent non 0 exit code if no results

- services/ui-src/src/components/EditUser/EditUser.jsx
There was a seds bug where if admin unassigned a user from a state (usually just by assigning the user to another role), upon next login of said user, there would be a 500 forbidden error when trying to select a state. This was due to a `"null"` string being passed into the state value instead of just good ol' `null`. 
All I did here was change from a "null" string to the actual null value and it resolved the issue. 
CMDCT-3252
---
1. Pull down my `cmdct-3252` branch locally in seds and run locally
2. Log into seds as `adminuser@test.com`
3. Go to view/edit users
4. select a user that you have the credentials to log in with (look for the `stateuser@test.com` user) 
5. change the role of the user and make sure that when you Update User, there is no state selected
6. After the user has been …
> CMDCT-3252: fixing issue with user setting state after admin unassigning state

- package.json
- yarn.lock
Custom Lambdas are triggering warnings in security hub. These are used by the serverless framework as part of the deployment process. Upgrading to 3.39 should resolve it.
CMDCT-3897
---
Deployments succeed. Custom lambdas for cw-role || existing-s3 are on node 18, not 16.
Verified: 
---
---
---
> [CMDCT-3897] Upgrade Serverless - Custom Lambda Runtime

- services/ui-src/package.json
- services/ui-src/yarn.lock
Browserify is used to convert nodejs-style "`require()`" imports to a syntax that browsers can understand. But:
* The string "browserify" didn't appear in our UI code (outside of package.json and yarn.lock files, and those appearances were not invocations).
* The string "require" does not appear in our UI code (outside of yarn.lock, and a comment in Question.jsx).
* We are using Vite to build / bundle the app, which should be able to handle this type of import syntax conversion (if we ever need it (which we won't)).
Therefore, I am confident that removing the dependency from package.json will not break the app.
CMDCT-3850
---
There's really nothing to test here. I guess once we merge main we should double-check that the app still comes up in the dev environment.
n/a
---
- ~[ ] I have …
> Remove browserify dependency

- services/ui-auth/package.json
- services/ui-auth/yarn.lock
Parsing xml is not part of our app.
I suspect this dependency was added as a workaround for a past vulnerability in a dependency. According to our lockfile today, it is only holding us back.
n/a
---
n/a
n/a
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~
- ~[ ] I have performed a self-review of my code~
- ~[ ] I have manually tested this PR in the deployed cloud environment~
---
- ~[ ] Product: This work has been reviewed and approved by product owner, if necessary~
- ~[ ] These changes are significant enough to …
> Remove fast-xml-parser.

- services/ui-src/src/utility-functions/exportFunctions.js
- services/ui-src/src/utility-functions/exportFunctions.test.js
Fixes error: `TypeError: Cannot read properties of undefined (reading 'toString')`
This error was not caught in development because our canned test data does not include any `undefined` values in the user list. The live environments sometimes do.
n/a
---
This would be a real pain to actually test locally. I think you'd need to spin up the dynamo db admin page, then delete some of the properties from an object in the user table, and then follow the test instructions from #14948.
Frankly, I wouldn't.
n/a
---
- ~[ ] I have performed a self-review of my code~
---
- ~[ ] Product: This work has been reviewed and approved by product owner, if necessary~
_If …
> Allow for undefined values in user table export

- .github/branchNameValidation.sh
- .github/workflows/pull-request.yml
- .pre-commit-config.yaml
Serverless automates naming of resources based on the branch name, and long names can often overrun the automatically generated limit. We've shortened this limit before, but we're still seeing errors pop up. Shorten the length limit to 20 for all repos.
CMDCT-3700
---
checkout this branch, create a new branch that is longer than 20 characters, and make a change on your branch (e.g. change the text on a button)
run pre-commit run and you should see the error message Bad branch name detected in your terminal. A branch name under 20 characters that starts with a letter should pass this pre-commit check.
---
---
---
_convert to a different template: [test → …
> limit branch name to 20 characters

- services/ui-src/src/components/Users/Users.jsx
Typically, users have a `states` property that is an array of state abbreviations associated with that user. Sometimes that property may be missing. Sometimes it may be a string instead.
With this PR, we will handle those cases gracefully, and still display the table as best we can.
Eventually, I intend to circle back and run migrations to ensure `user.states` is always a string array - but today is not that day.
n/a
---
To view the user table, log in as admin and choose "View / Edit Users". The table will display fine, as it always has, because our seed data doesn't contain any of these edge cases.
You could test the logic by making manual updates in DynamoDB, locally or in this environment's branch. To be frank, I think the easiest way to test will be to merge this PR and see if the …
> Fix state abbr sorting edge case in user table

- deployment/app.ts
- deployment/import_instructions.md
- deployment/stacks/data.ts
- deployment/stacks/parent.ts
- deployment/stacks/ui-auth.ts
- deployment/stacks/ui.ts
- deployment/stacks/with_imports/parent.ts
- deployment/stacks/with_imports/ui-auth.ts
- deployment/stacks/with_imports/ui.ts
- deployment/stacks/without_imports/parent.ts
- services/ui-auth/serverless.yml
- services/ui/serverless.yml
- src/run.ts
This mostly tweaks the way we are doing the importing so that the main cdk setup can be used as is and we just run special commands during importing. For more details check out `deployment/import_instructions.md`.
CMDCT-4194
---
You are welcome to try following the `deployment/import_instructions.md` and see if it all makes sense and enables you to import resources from a serverless stack.
NA
---
---
---
> CMDCT-4194 cdk side, creating a better way to import resources from serverless including Cognito UserPool

- services/database/serverless.yml
For this serverless side change we are just making sure that dynamo tables are retained when the serverless stacks are destroyed.
CMDCT-4186
---
Deploy the stack on this branch and see that it creates several serverless stacks. Then run the destroy command and see that it destroys lots of stuff but importantly not the dynamo tables.
NA
---
---
---
> CMDCT-4186 - serverless side, prep dynamo tables so that they are retained

- README.md
- deployment/deployment-config.ts
- deployment/prerequisites.ts
- deployment/stacks/api.ts
- deployment/stacks/parent.ts
- deployment/stacks/ui.ts
- src/run.ts
Prerequisite resources instead of being created in each stack or each !isDev stack will exist in a single stack that is created in each AWS account.
CMDCT-4226
---
You can check out the existing 4226 stack and it's cloudfront url: 
https://d2obsaoedfxcpv.cloudfront.net/
Unfortunately seds-prerequisite stack and jon-cdk stack can't both exist at the same time so let me know if you want to see seds-prerequisite in action and I can temporarily destroy jon-cdk stack (again, I already did this a couple times to test).
NA
---
---
---
> CMDCT-4226 - sets up deploy-prerequisites to create resources needed in AWS account

- services/app-api/handlers/users/post/updateUser.js
- services/ui-src/src/components/EditUser/EditUser.jsx
- services/ui-src/src/components/EditUser/EditUser.test.jsx
This PR locks down the username field of the EditUser page (which is visible only to admins). Previously, this page could be used to change the username, but there shouldn't be a need to do so - username will come from Cognito.
There is a possibility that this functionality will be needed in the future; requirements analysis is ongoing, and we may someday add this ability back.
This PR also adds stricter validation for the fields that _can_ be updated from the EditUser page.
CMDCT-4234
---
1. Log in as an admin user
2. Go to View / Edit Users
3. Click a username to go to the Edit page
4. Note that the username field is disabled - as are all string fields
5. Attempt to edit role or state. Note that the update succeeds.
---
---
_If …
> Disallow editing of user properties that come from Cognito

- services/app-api/handlers/users/post/updateUser.js
- services/ui-src/src/components/EditUser/EditUser.jsx
- services/ui-src/src/components/EditUser/EditUser.test.jsx
Dev -> Val
- Further restricted potential for editing usernames into a csv attack
> Disallow editing of user properties that come from Cognito (#15033)

- src/run.ts
- src/slsV4BucketPolicies.ts
There was issue with run local needing aws creds. This should solve it.
CMDCT-4324
---
Checkout this branch. Run local should not ask for creds.
NA
---
---
---
> CMDCT-4324 - gets run local not needing credentials

- deployment/stacks/deployFrontend.ts
- deployment/stacks/env-config.template.js
- deployment/stacks/parent.ts
- deployment/stacks/ui-auth.ts
A few things we've realized are better than not having for termination protection, invalidating cloudfront consistently, and always assuming okta will be there (because it will, even if it doesn't always work).
CMDCT-4360
---
Use the app, it should still work :)
I tested pushing a commit with no changes to make sure it created an invalidation still and it did:
https://github.com/Enterprise-CMCS/macpro-mdct-seds/actions/runs/13633717265/job/38107202761
---
---
---
> CMDCT-4360 - termination protection + always invalidation + okta always

- deployment/constructs/lambda-dynamo-event.ts
- deployment/deployment-config.ts
- deployment/stacks/api.ts
- deployment/stacks/parent.ts
- deployment/utils/vpc.ts
- package.json
- services/app-api/handlers/kafka/post/dataConnectSource.js
- services/app-api/handlers/kafka/post/postKafkaData.js
- yarn.lock
This will fix a kafka problem. Hopefully that's all we need to do.
CMDCT-4390
---
Check postKafta and dataConnect logs to see there is no error.
Also, super uncool but I had to change the version for cdk because the internet is a spooky place.
How does this work?:
https://github.com/aws/aws-cdk/releases
Says the latest version is 2.182.0
Then check out yarn's versions
https://yarnpkg.com/package?q=aws-cdk&name=aws-cdk
There they've removed 2.182.0 and added several with the middle number in the thousands. The thousands introduces some things we'll need to change.
---
---
---
_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → …
> CMDCT-4390 - fixes kafka getting non-existent tables

- services/app-api/handlers/forms/post/generateQuarterForms.js
- services/app-api/handlers/forms/post/generateQuarterForms.test.js
- services/app-api/libs/time.js
- services/app-api/libs/time.test.js
Putting time-related functions in their own file makes them easier to mock when unit testing other business logic.
In fact, this fixes the tests for generateQuarterForms, which were failing because this function was _not_ being mocked.
I don't know what was wrong with my mocking code before, but it is now simpler and definitely works.
n/a
---
This PR has no intentional behavioral changes. If the unit tests pass, we're in good shape.
---
---
---
> Move calculateFormQuarterFromDate to its own file

- .github/workflows/git-secrets.yaml
- deployment/stacks/ui-auth.ts
- deployment/stacks/ui.ts
This change will mean that we no longer have issues destroying branches which destroys the stack.
CMDCT-4622
---
The app still works the same.
NA
---
---
---
> CMDCT-4622 gets cloudfront logging to stop breaking destroys for ephemeral apps

- .github/setBranchName.sh
- .github/workflows/dependabot-auto-merge.yml
- .github/workflows/deploy.yml
Undo the removal of dependabot:
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/507/files
This PR reenables the following:
- Branch names for dependabot are converted to an md5sum and shortened
- Dependabot branches deploy
- Dependabot branches auto-merge assuming required checks pass
CMDCT-4375
---
Once this is merged, monitor future PRs
---
---
> [CMDCT-4375] Enable dependabot automerge on success

- deployment/stacks/ui.ts
Bangbay found an error in the tealium code change -- tealium-tags.cms.gov wasn't whitelisted so utag.sync.js and utag.js were blocked from loading.
CMDCT-5066
---
Testing today at meeting
> [SEDS] Whitelist tealium-tags.cms.gov

- deployment/stacks/ui.ts
All apps should retain cloudfront logs for 30 months or 3 years
CMDCT-5123
---
---
---
---
> add lifecycle rule for log expiration

- deployment/stacks/ui.ts
Was seeing this error in the dev: 
> Refused to connect to 'https://dap.digitalgov.gov/Federated.js.map' because it violates the following Content Security Policy directive: "connect-src https://*.[amazonaws.com/](http://amazonaws.com/) https://*.[amazoncognito.com](http://amazoncognito.com/) https://www.google-analytics.com/ https://*.[launchdarkly.us](http://launchdarkly.us/) https://adobe-ep.cms.gov/ https://adobedc.demdex.net/".
This PR adds https://dap.digitalgov.gov/ to the the `connect-src` portion
Testing with BlastX is rescheduled for tomorrow 😳 
CMDCT-5066
> add dap url to connect-src

- services/database/scripts/migrateStateFormStatus.js
* Log less from the DynamoDB client. If something goes wrong it will log that, but if everything is fine it will be quiet.
* Include timestamps in all other log messages.
* Use BatchWriteCommand instead of PutCommand. This required a significant reorganization of the script, and the logging of counts will no longer be 100% accurate in the event of an error. But the speedup takes this script from an estimated ~15 minutes in production to an estimated ~30 seconds. Combined with an expected AWS deployment of 4 minutes and change, that gets us to an estimated 5 minutes for the entire deployment.
This PR replaces #15181.
CMDCT-3884
---
You can't. But I did, in every way I knew how.
---
---
--- …
> Improve status_id ETL script
